{
 "title": "Backups",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(restic_repository_snapshot_total,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Size",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(restic_repository_snapshot_total_size_bytes{instance=~\"$instance\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(restic_s3_total_size_bytes{instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fastest growing",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(topk (5, restic_repository_snapshot_latest_size_bytes > 0))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Backups",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "restic_repository_snapshot_total{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "restic_repository_snapshot_total_size_bytes{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "restic_repository_snapshot_latest_size_bytes{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "restic_repository_snapshot_latest_time{instance=~\"$instance\"} * 1000",
     "legendFormat": "__auto"
    },
    {
     "expr": "restic_s3_total{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "restic_s3_total_size_bytes{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "restic_s3_latest_size_bytes{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "restic_s3_latest_time{instance=~\"$instance\"} * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=\"hetzner-restic\",instance=~\"$instance\"}"
    }
   ]
  }
 ]
}